### ISSUE TITLE
RDSに初期データを登録する

### ISSUE THREAD

**Issue by keitakn** [nekochans/lgtm-cat#16]
# Doneの定義
- https://github.com/nekochans/lgtm-cat-frontend/blob/main/src/infrastructures/utils/imageData.ts に登録されている画像データがRDSの本番用のテーブルに記録されている事

**Comment by kobayashi-m42** [comment]
@keitakn 下記の通りSTGで検証したよ！もし問題なければ、本番に実施しようと思う！


RDSに登録するためのクエリを作成。
STGで実行し、データが登録されることを確認した。(insert したデータは削除済み)

実行前の件数：19
実行後の件数：192

クエリの実行結果
```
Query OK, 173 rows affected (0.02 sec)
Records: 173  Duplicates: 0  Warnings: 0
```

<details>
<summary>SQL</summary>

INSERT INTO lgtm_images
    (path, filename)
VALUES ('2021/03/16/00', '35afef75-2d6d-4ca1-ab00-fb37f8848fca'),
       ('2021/03/16/00', '71a7a8d4-33c2-4399-9c5b-4ea585c06580'),
       ('2021/03/16/00', '98f86ac2-7227-44dd-bfc9-1d424b45813d'),
       ('2021/03/16/00', 'bf3bbfb8-56d3-453d-811c-0f5fd9dfa4d0'),
       ('2021/03/16/00', '44dc9b25-a0df-4726-a2bd-fccb1e0e832e'),
       ('2021/03/16/00', '62b7b519-9811-4e05-8c39-3c6dbab0a42d'),
       ('2021/03/16/01', '6c7ab983-4aa1-4af4-ab37-f1327899cc26'),
       ('2021/03/16/01', 'e549cf62-c8e2-4729-af9e-b35e27bb34e3'),
       ('2021/03/16/01', 'e62cf588-057c-43a1-82a0-035d7c0e67bf'),
       ('2021/03/16/22', '03b4b6a8-931c-47cf-b2e5-ff8218a67b08'),
       ('2021/03/16/22', '1ddee797-84ad-42e6-850b-da1fe9d3226a'),
       ('2021/03/16/22', '26d12d67-3f54-4887-ab9f-fd04871574f0'),
       ('2021/03/16/22', '31280089-90c6-44cd-8ab6-f2df95739eae'),
       ('2021/03/16/22', '34c7a37e-8504-4c12-924a-454d98458afd'),
       ('2021/03/16/22', '385f6909-8dd9-41c3-874d-b36c1da54ab2'),
       ('2021/03/16/22', '3b1fbf6c-ed19-45b8-9cd7-12e5ba08774e'),
       ('2021/03/16/22', '406be7e8-8908-458e-b083-5c60cf58cf1e'),
       ('2021/03/16/22', '4a77293c-cf7c-4478-b695-69fdf5baec45'),
       ('2021/03/16/22', '4ecfd97c-677b-4321-95bb-7270b4ef03b5'),
       ('2021/03/16/22', '4f33db82-4aa6-468e-b0ac-6148e245bbcf'),
       ('2021/03/16/22', '5863a89c-4d4e-4f00-bf08-f1ed45cd23cb'),
       ('2021/03/16/22', '655903e9-befc-4fc5-b937-f7faccd2ba25'),
       ('2021/03/16/22', '7f3d3e00-71af-48f2-beac-5eab0cc09ff4'),
       ('2021/03/16/22', '8a3a1c22-1f1b-4989-9768-29d8fbf728cd'),
       ('2021/03/16/22', '8e1a13da-5a88-4fa6-9c7e-3c67d82adfbc'),
       ('2021/03/16/22', 'a2a132bd-bd9e-47d9-9536-ca838294b323'),
       ('2021/03/16/22', 'a66dd7da-3105-4806-8c58-6fc66a0a3d04'),
       ('2021/03/16/22', 'afc54525-7611-43bb-b738-3cdf13947957'),
       ('2021/03/16/22', 'ba923c4e-946a-4215-b074-44a3b848b637'),
       ('2021/03/16/22', 'bdfef72a-5b0a-4c85-b0db-471321443c1d'),
       ('2021/03/16/22', 'c18a9260-4cc6-43f7-93e2-83ebbfb6186c'),
       ('2021/03/16/22', 'ca3ae851-732e-4160-a214-6c918eaca85b'),
       ('2021/03/16/22', 'd2b09644-a65d-4063-b4e8-39d9720743e0'),
       ('2021/03/16/22', 'd4a982e0-d3ca-4a93-83da-c5acd4726e88'),
       ('2021/03/16/22', 'e3fe2715-4155-45fc-b1cc-916db866f78f'),
       ('2021/03/16/22', 'ed62c9cf-ca00-47a4-ac56-d280a400f9f8'),
       ('2021/03/16/22', 'ff92782d-fae7-4a7a-b042-adbfccf64826'),
       ('2021/03/16/23', '137dbc7a-4aa2-4d99-9321-fc3e74b3ba94'),
       ('2021/03/16/23', '19b15db9-ac6e-4e9c-96ab-8984a2b280ea'),
       ('2021/03/16/23', '224b8d11-33eb-48ac-9d86-a9b151ace825'),
       ('2021/03/16/23', '27ad3952-8b59-47e0-997a-96cd727ba14d'),
       ('2021/03/16/23', '46b1d895-d46b-4a5c-8fc1-78725efded9f'),
       ('2021/03/16/23', '46f702ca-43c7-49fa-8714-ecf1688c95e1'),
       ('2021/03/16/23', '474a4307-2d2b-471b-8bfb-1b73d2556d18'),
       ('2021/03/16/23', '518dea4f-a399-42fc-af5a-876355b9f660'),
       ('2021/03/16/23', '5947f291-a46e-453c-a230-0d756d7174cb'),
       ('2021/03/16/23', '5e6f48f1-fae3-497d-bf81-0df8223cc671'),
       ('2021/03/16/23', '6332ceea-e9cd-4c05-ae1a-6a61140966c3'),
       ('2021/03/16/23', '667b6012-586f-4906-9092-8b385fb6fe9f'),
       ('2021/03/16/23', 'ac9c977c-5794-4c51-b719-f715d9db2eaf'),
       ('2021/03/16/23', 'aed16e28-93c1-4cd6-9969-23f4363afa83'),
       ('2021/03/16/23', 'b4c6324d-e358-4080-bad0-17d4821e456a'),
       ('2021/03/16/23', 'e17e623f-6387-4910-9926-2cf8d429aa19'),
       ('2021/11/16/22', '01276cb2-54c3-48a1-bd4b-a7abd53c798e'),
       ('2021/11/16/22', '05273ff6-0bf4-4fc9-ada5-0bd3ff3c282f'),
       ('2021/11/16/22', '06a18828-c134-4a24-8c68-038369ced611'),
       ('2021/11/16/22', '08b6994e-c8b5-4db3-8b41-2de17dd4e9f8'),
       ('2021/11/16/22', '0bfe2a10-777d-4d28-950f-00db9e21b10a'),
       ('2021/11/16/22', '1147b8a0-5efe-4815-a7e8-6affb1bab227'),
       ('2021/11/16/22', '142da183-ae49-4ca8-bdaf-e9502d43bd81'),
       ('2021/11/16/22', '188a6dfd-31d7-43be-bf9e-61017147ca8d'),
       ('2021/11/16/22', '192b3a60-cf93-40fa-b9f5-3021b46a1543'),
       ('2021/11/16/22', '19afd71e-9860-4b26-9e27-9bc0f8d16f57'),
       ('2021/11/16/22', '1a32c50c-8f54-4563-9a8b-317cdc0ae6ce'),
       ('2021/11/16/22', '2089aa83-7584-4451-96c6-7e2d4ba8ec2a'),
       ('2021/11/16/22', '22e90313-3730-4459-8c20-69397afb9e43'),
       ('2021/11/16/22', '243efe15-a10e-430e-8915-46a3a802f602'),
       ('2021/11/16/22', '27878370-230b-4505-95f7-c6cf47be04e8'),
       ('2021/11/16/22', '28da898f-1365-4c0e-8de0-f7aff2d91528'),
       ('2021/11/16/22', '28e85f1c-9a13-42ae-a206-28a558eff2e8'),
       ('2021/11/16/22', '2b928227-f3fd-4aaa-b344-ae06fa3771cf'),
       ('2021/11/16/22', '310eddb0-d18b-4687-936b-9009ea28ea71'),
       ('2021/11/16/22', '34e65559-3428-4a16-83ee-b98fa521c08b'),
       ('2021/11/16/22', '3696dde3-3138-49f5-aeb5-ed5c820dc686'),
       ('2021/11/16/22', '3908cf2f-22fa-44ad-ba0e-89c6c7ffaeef'),
       ('2021/11/16/22', '3928d184-a824-4351-a431-e0ff1d333d1d'),
       ('2021/11/16/22', '393e8b74-28e6-41cc-9685-e536d55f4288'),
       ('2021/11/16/22', '395be7fb-3a25-4373-9a2e-ab92dc9abb4a'),
       ('2021/11/16/22', '395dc0d1-03aa-49ef-897a-996fe6da0cc8'),
       ('2021/11/16/22', '3c5ae6bf-81cb-4fbb-9eae-76d0002b11c5'),
       ('2021/11/16/22', '3daf6023-6c7c-4aee-8200-97771a4deb72'),
       ('2021/11/16/22', '408d5954-24ee-4184-a01f-6ef4eb7de907'),
       ('2021/11/16/22', '43be5e03-ceb4-49f1-ae30-e5389abd2e5b'),
       ('2021/11/16/22', '474af724-cc5f-4dfe-943e-adc085006aab'),
       ('2021/11/16/22', '47696595-3155-484c-98fd-3cb51e451f71'),
       ('2021/11/16/22', '4a32f2b4-507c-4a64-8afe-28ebb5bb5658'),
       ('2021/11/16/22', '4aac7db1-ebfa-46bc-84a3-25b7a12c0ca2'),
       ('2021/11/16/22', '4af05047-7a29-44e1-83cd-22f01c1d524a'),
       ('2021/11/16/22', '4eaae221-fb68-4aef-a9bf-21ab04395bf3'),
       ('2021/11/16/22', '5092121f-65da-47bf-ab8c-a2fb2d510efb'),
       ('2021/11/16/22', '52a5e330-c0b7-4357-b0a2-e30e3fdd7476'),
       ('2021/11/16/22', '54e2630d-ffef-41d4-a3b5-81e4b2ee68fe'),
       ('2021/11/16/22', '5906274f-ca17-4976-8f43-54aa3ee391d5'),
       ('2021/11/16/22', '5c706c5e-3d76-4090-bb3a-01a0eedb7f4a'),
       ('2021/11/16/22', '5efffe2e-c686-4239-8bec-f7b1912bb220'),
       ('2021/11/16/22', '5fa7541f-5346-428d-adbd-79d3ac60c532'),
       ('2021/11/16/22', '68b24c42-adc6-46be-ba47-3013fe8eaceb'),
       ('2021/11/16/22', '6a583892-bd79-4511-b857-4d7312036ed9'),
       ('2021/11/16/22', '6b7f872b-5988-449a-abd0-317b6c3e47b0'),
       ('2021/11/16/22', '6b9ede79-d3c3-4dcf-993c-33140ecf86d4'),
       ('2021/11/16/22', '6cb07bce-67a8-496e-a6c5-febfb435a9a5'),
       ('2021/11/16/22', '6e46ab0a-60ac-4c6b-840c-6d2d08de1689'),
       ('2021/11/16/22', '74046d97-439f-4e11-ad18-a756bcea6131'),
       ('2021/11/16/22', '7542a82f-87d2-4c48-aee7-660b8a7bd3df'),
       ('2021/11/16/22', '7600743b-908b-4743-a081-b171505c8bb3'),
       ('2021/11/16/22', '76de320a-b44c-4134-83f1-b874c4ff8663'),
       ('2021/11/16/22', '7996ecc3-6050-4c87-9348-7547b4757697'),
       ('2021/11/16/22', '7a45ffc7-e664-468e-84d3-96a9b524779a'),
       ('2021/11/16/22', '7b5c51fc-50ef-48db-88dc-1ef54661e269'),
       ('2021/11/16/22', '7cc0a118-0358-4794-b0d4-37a63949c968'),
       ('2021/11/16/22', '82f46511-f5c8-4488-a090-871e9b7b1a65'),
       ('2021/11/16/22', '8302f89d-0fda-409d-b0db-0cef2283ed8b'),
       ('2021/11/16/22', '83408230-f157-4133-ba4f-8cfbe4f80d71'),
       ('2021/11/16/22', '850b50f2-453f-4b11-a5d4-48d178387bb7'),
       ('2021/11/16/22', '87774cf9-109d-4951-afd8-59a59211af05'),
       ('2021/11/16/22', '88e82798-cc70-45c1-a1fe-17fe05658e22'),
       ('2021/11/16/22', '8b9470d2-0271-42b6-87b9-96679a3c587b'),
       ('2021/11/16/22', '8bb24085-ad0e-4b6d-b5e0-b4da797b13a9'),
       ('2021/11/16/22', '8dc0dfd0-bb86-4d03-ad1d-e541c1a5d3ec'),
       ('2021/11/16/22', '8eebd8bb-df93-4f64-99fc-3415ac5ec2a3'),
       ('2021/11/16/22', '93331fd9-96b5-4802-ba04-9095bc57ef15'),
       ('2021/11/16/22', '93646290-d9cd-41e7-a136-8942ebf6bc12'),
       ('2021/11/16/22', '93f423f6-24e6-48d0-801d-909bec1c668f'),
       ('2021/11/16/22', '975da28e-5ce0-4b0a-b656-9cd6f4c7a729'),
       ('2021/11/16/22', '99ac540a-07d3-4033-8800-75d13588c74b'),
       ('2021/11/16/22', '99c8f345-b8eb-483e-86c5-258ebfbb9156'),
       ('2021/11/16/22', '99da5c4e-5d61-4543-9199-1f7a410530cc'),
       ('2021/11/16/22', '9a187ea3-ba17-4107-910b-0ff89c987ca7'),
       ('2021/11/16/22', '9b46903b-f339-499e-880d-36a6db246651'),
       ('2021/11/16/22', '9ba477eb-e9c6-4984-b15c-259d19dd34cf'),
       ('2021/11/16/22', '9c3567bb-017d-4e17-ba2d-ecc58b4fe6a0'),
       ('2021/11/16/22', '9d6c5716-5085-4870-88e4-5d83b0077718'),
       ('2021/11/16/22', 'a0b45b02-6fb9-4d67-a8be-1bfe14017757'),
       ('2021/11/16/22', 'a1629516-1ec4-4585-ade2-9d3c3c3e9414'),
       ('2021/11/16/22', 'a8588324-b184-4824-af0f-d2c489789c32'),
       ('2021/11/16/22', 'a95f34d4-edf9-4dab-b502-2db205375f3c'),
       ('2021/11/16/22', 'ac71e409-b7a5-4e27-9508-09d9c8aa7584'),
       ('2021/11/16/22', 'ae21402b-64a6-4697-bfac-06b9766f75af'),
       ('2021/11/16/22', 'af637936-267e-49c0-9618-2960b1b1f063'),
       ('2021/11/16/22', 'b1cdbc87-bf28-4c19-8afe-5fb6a61d3341'),
       ('2021/11/16/22', 'b24ee663-c30f-4d87-88ff-5c10be18c676'),
       ('2021/11/16/22', 'b459c655-dabd-4423-b437-362bb8b68471'),
       ('2021/11/16/22', 'b6ebf089-535c-4f33-977e-cddd46601bcd'),
       ('2021/11/16/22', 'b75c5e08-12be-4026-a89a-8d8493a9457b'),
       ('2021/11/16/22', 'b80e592b-e32d-4a9d-a4a2-f138785bb8ec'),
       ('2021/11/16/22', 'b9974772-4771-4e19-b42c-88ba9cc28aee'),
       ('2021/11/16/22', 'bd2d578a-98ec-45f2-a990-87d30caa10e3'),
       ('2021/11/16/22', 'be1e62a0-2c48-4460-a48e-c4ce87760cd3'),
       ('2021/11/16/22', 'c037ac5a-53a1-42f8-9375-034e94962293'),
       ('2021/11/16/22', 'c0ae3bfc-0dc3-49ea-a3b3-95b72b6407ba'),
       ('2021/11/16/22', 'c512c683-d9ff-4a0c-b668-a24f7c6c84f2'),
       ('2021/11/16/22', 'c6359e2d-ea6c-4e72-9bef-0317f304c043'),
       ('2021/11/16/22', 'c8e26110-148f-4885-be87-f4e17b2ccb00'),
       ('2021/11/16/22', 'd0c17d9d-fe1a-4000-8b6a-b48e5f904b52'),
       ('2021/11/16/22', 'd218bd8d-9ddd-492f-a91d-e35050697dfb'),
       ('2021/11/16/22', 'd462b567-7427-422a-a860-762b5296ab5a'),
       ('2021/11/16/22', 'd54fd1e5-6a61-4ef0-bad9-4c6758424b37'),
       ('2021/11/16/22', 'd90d5199-4b64-4185-b925-4d7c91eda904'),
       ('2021/11/16/22', 'dba3ed18-1664-4d09-b20a-0a5033b6e93f'),
       ('2021/11/16/22', 'dc578716-9012-4160-b337-44db92dcf7a1'),
       ('2021/11/16/22', 'ded95387-5136-4d3a-bde6-deb523608a59'),
       ('2021/11/16/22', 'e04192d9-8abc-41cf-9447-33dc591e8855'),
       ('2021/11/16/22', 'e25133e1-52b1-45c4-ba93-fdd698f57753'),
       ('2021/11/16/22', 'e338c3cb-2966-4a57-813f-a9168710e5d7'),
       ('2021/11/16/22', 'e574716a-ae98-403c-b70c-878e4fedd01e'),
       ('2021/11/16/22', 'f44e674b-cbfe-4da4-bb72-e7d9b80c04b7'),
       ('2021/11/16/22', 'f5ac6b43-a694-4690-bf55-5c7b897a4f47'),
       ('2021/11/16/22', 'f65a447c-fe8c-4e4b-9ec6-b549b6f13470'),
       ('2021/11/16/22', 'f878e357-8b78-42d9-b400-1032221900cd'),
       ('2021/11/16/22', 'f9a5ef71-df87-4f64-a5d7-6e8de93998e7'),
       ('2021/11/16/22', 'fd866a6d-8641-4d8b-b6b1-017ef93b8748'),
       ('2021/11/16/22', 'fe780d70-9f04-4a41-a840-cdd990fb75b3'),
       ('2021/11/16/22', 'ff9c6181-4a63-4445-9416-fd87b7d86914');

</details>

**Comment by keitakn** [comment]
@kobayashi-m42 ありがとう🐱！
問題なさそうだから時間ある時に本番もよろしく👍

**Comment by kobayashi-m42** [comment]
@keitakn 本番も実施したから、この課題はクローズするね！
